# Generated by Django 4.2.5 on 2023-10-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
