# Generated by Django 4.2.5 on 2023-10-10 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('d798313a-6240-43eb-b01c-1f611a3a9182'), editable=False, primary_key=True, serialize=False),
        ),
    ]
