# Generated by Django 4.2.5 on 2023-10-05 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('f0a01c3d-e997-45a9-a0dc-88e6bcbc7411'), editable=False, primary_key=True, serialize=False),
        ),
    ]
