# Generated by Django 4.2.5 on 2023-10-05 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('31f238d0-026c-4336-bec2-2533655f83df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
