# Generated by Django 4.2.5 on 2023-10-12 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('2278b8a4-b8d6-4a8c-8939-0bde77f78f1d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
