# Generated by Django 4.2.5 on 2023-10-05 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('416d0433-973c-47a6-93be-a695a9474445'), editable=False, primary_key=True, serialize=False),
        ),
    ]
