# Generated by Django 4.2.5 on 2023-10-09 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(default=uuid.UUID('3e541f81-b711-470c-a915-af35949d6911'), editable=False, primary_key=True, serialize=False),
        ),
    ]
